ims/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('cat', views.cat, name='cat'),
    path('brand', views.brand, name='brand'),
    path('product', views.product, name='product'),
    path('edit/<str:pk>/', views.UpdateProduct, name='edit'),
    path('update_brand/<str:pk>/', views.UpdateBrand, name='update_brand'),
    path('update_cat/<str:pk>/', views.UpdateCat, name='update_cat'),
    path('delete_product/<str:pk>/', views.DeleteProduct, name='delete_product'),
    path('delete_brand/<str:pk>/', views.DeleteBrand, name='delete_brand'),
    path('delete_cat/<str:pk>/', views.DeleteCat, name='delete_cat'),
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutPage, name='logout'),
    path('staff/', views.staffPage, name='staffpage'),
    path('staffproduct/', views.StaffProduct, name='staffproduct'),
    path('productdetails/<str:pk>/', views.ProductDetails, name='productdetails'),
    path('report/', views.report, name='report'),
    path('productdetails_staff/<str:pk>/', views.StaffProductDetails, name='productdetails_staff'),
    path('count/<str:pk>/', views.recordCount, name='count'),
    path('upload', views.simple_upload, name= 'upload'),
    path('export_sales', views.export_sales_csv, name= 'export_sales'),
    path('export_count', views.export_count_csv, name= 'export_count'),
    path('export_restock', views.export_restock_csv, name= 'export_restock'),
    path('debt', views.debtors, name= 'debt'),
    path('update_debt/<str:pk>/', views.UpdateDebt, name='update_debt'),
    path('delete_debt/<str:pk>/', views.DeleteDebt, name='delete_debt'),
    
]

ims/models.py
from unicodedata import category
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=0, blank=True, null=False)
    batch_no = models.IntegerField(blank=True, null=True)
    unit = models.CharField(max_length=50, blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    reorder_level = models.IntegerField(default=10, blank=True, null=False)

    choices = (
        ('Available', 'Item is currently available'),
        ('Restocking', 'Currently out of stock'),
    )
    status = models.CharField(max_length=20, choices=choices, default="Available", blank=True, null=True)# Available, Restocking
    last_updated = models.DateField(auto_now=True,)
    timestamp = models.DateTimeField(auto_now_add=True,)
    choices = (
        ('General', 'General'),
        ('Promo', 'Promo'),
    )
    mode_of_sales = models.CharField(max_length=50, choices=choices,default="General", blank=True, null=True)
    quantity_sold = models.IntegerField(default=0, blank=True, null=True)
    total_price = models.IntegerField(default=0, blank=True, null=True)
    quantity_restocked = models.IntegerField(default=0, blank=True, null=True)
    count = models.IntegerField(default=0, blank=True, null=True)
    store = models.IntegerField(default=0)
    variance = models.IntegerField(default=0)
    available = models.IntegerField(default=0)
    history = HistoricalRecords()
    
    
    def __str__(self):
        return self.name
    
class ProductReport(models.Model):
    name = models.CharField(max_length=150, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=0, blank=True, null=False)
    batch_no = models.IntegerField(blank=True, null=True)
    unit = models.CharField(max_length=50, blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    reorder_level = models.IntegerField(default=10, blank=True, null=True)
    

    choices = (
        ('Available', 'Item is currently available'),
        ('Restocking', 'Currently out of stock'),
    )
    status = models.CharField(max_length=20, choices=choices, default="Available", blank=True, null=True)# Available, Restocking
    last_updated = models.DateField(auto_now_add=True, auto_now=False, null=True)
    timestamp = models.DateTimeField(auto_now_add=False, auto_now=False, null=True)
    choices = (
        ('General', 'General'),
        ('Promo', 'Promo'),
    )
    mode_of_sales = models.CharField(max_length=50, choices=choices,default="General", blank=True, null=True)
    quantity_sold = models.IntegerField(default=0, blank=True, null=True)
    total_price = models.IntegerField(default=0, blank=True, null=True)
    amount = models.IntegerField(default=0, blank=True, null=True)
    quantity_restocked = models.IntegerField(default=0, blank=True, null=True)
    count = models.IntegerField(default=0, blank=True, null=True)
    store = models.IntegerField(default=0, blank=True, null=True)
    variance = models.IntegerField(default=0, blank=True, null=True)
    available = models.IntegerField(default=0, blank=True, null=True)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.name
    
    
class Staff(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=20)
    email = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
class Debtor(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    customer_name = models.CharField(max_length=1000)
    amount_paid = models.FloatField()
    amount_owed = models.FloatField()
    payment_completed = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()
    
    def __str__(self):
        return self.customer_name

ims/views.py
from urllib import response
from django import contrib
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from .models import Product, Category, Brand, Staff, ProductReport, Debtor
from .forms import CatForm, BrandForm, CountForm, ProductForm, CreateUserForm, ReorderForm, RestockForm, SalesForm, ProductUpdateForm, ProductReportForm, DebtForm, DebtUpdateForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated_user, allowed_users, admin_only
from django.contrib.auth.models import Group
from .resources import ProductResource
from tablib import Dataset
from django.core.paginator import Paginator
import csv
from django.http import HttpResponse, JsonResponse
import datetime
from .filters import reportFilter
from datetime import date
from dateutil.relativedelta import relativedelta

@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'Account successfully created for ' + username)
            return redirect('login')
    context = {
        'form':form
    }
    return render(request, 'ims/register.html',context)
    
@unauthenticated_user
def loginPage(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard')
        else:
            messages.info(request, 'Username or Password is not correct')

    return render(request, 'ims/login.html')

def logoutPage(request):
    logout(request)
    return redirect('login')


def staffPage(request):
    products = Product.objects.all()
    paginator = Paginator(Product.objects.all(), 5)
    page = request.GET.get('page')
    product_page = paginator.get_page(page)
    nums = "a" *product_page.paginator.num_pages
    
    context = {
        'products':products,
        'product_page':product_page,
        'nums':nums,
    }
    return render(request, 'ims/staffproduct.html', context)

@login_required(login_url=('login'))
@admin_only
def dashboard(request):
    products = Product.objects.all()
    cats = Category.objects.all()
    brands = Brand.objects.all()
    staffs = Staff.objects.all()
    reports = ProductReport.history.order_by('-quantity_sold')[:7]
    report = ProductReport.history.order_by('-quantity_restocked')[:7]
    pr = Product.objects.order_by('-available')[:7]
    
    total_staffs = staffs.count()
    total_products = products.count()
    total_cats = cats.count()
    total_brands = brands.count()

    context = {
        'pr':pr,
        'reports':reports,
        'report':report,
        'products':products,
        'cats':cats,
        'brands':brands,
        'total_products':total_products,
        'total_cats':total_cats,
        'total_brands':total_brands,
        'staffs':staffs,
        'total_staffs':total_staffs
    }
    return render(request, 'ims/dashboard.html', context)

@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def brand(request):
    brands = Brand.objects.all()
    form = BrandForm()
    if request.method == 'POST':
        form = BrandForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'successfully created')
            return redirect('brand')
    context = {
        'form':form,
        'brands':brands
    }
    return render(request, 'ims/brand.html', context)

@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def cat(request):
    cats = Category.objects.all()
    form = CatForm()
    if request.method == 'POST':
        form = CatForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'successfully created')
            return redirect('cat')
    context = {
        'form':form,
        'cats':cats
    }
    return render(request, 'ims/cat.html',context)

@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def product(request):
    products = Product.objects.all()
    paginator = Paginator(Product.objects.all(), 5)
    page = request.GET.get('page')
    product_page = paginator.get_page(page)
    nums = "a" *product_page.paginator.num_pages
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,  'successfully created')
            return redirect('product')
    context = {
        'form':form,
        'products':products,
        'product_page':product_page,
        'nums':nums,
    }
    return render(request, 'ims/product.html', context)

@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def UpdateProduct(request, pk):
    products = Product.objects.get(id=pk)
    form = ProductUpdateForm(instance=products)
    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, instance=products)
        if form.is_valid():
            form.save()
            print("Edited")
            messages.success(request, (products.name) + ' successfully updated')
            return redirect('product')
    context = {
        'form':form,
    }
    return render(request, 'ims/edit.html', context)


@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def UpdateBrand(request, pk):
    brands = Brand.objects.get(id=pk)
    form = BrandForm(instance=brands)
    if request.method == 'POST':
        form = BrandForm(request.POST, instance=brands)
        if form.is_valid():
            form.save()
            messages.success(request, (brands.name) + ' successfully updated')
            return redirect('brand')
    context = {
        'form':form,
    }
    return render(request, 'ims/edit.html', context)


@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def UpdateCat(request, pk):
    cats = Category.objects.get(id=pk)
    form = CatForm(instance=cats)
    if request.method == 'POST':
        form = CatForm(request.POST, instance=cats)
        if form.is_valid():
            form.save()
            messages.success(request, (cats.name) + ' successfully updated')
            return redirect('cat')
    context = {
        'form':form,
    }
    return render(request, 'ims/edit.html', context)


@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def DeleteProduct(request, pk):
    products = Product.objects.get(id=pk)
    if request.method == 'POST':
        products.delete()
        messages.success(request, 'successfully Deleted')
        return redirect('product')

    context = {
        'name':products
    }
    return render(request, 'ims/delete.html', context)


@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def DeleteBrand(request, pk):
    brands = Brand.objects.get(id=pk)
    if request.method == 'POST':
        brands.delete()
        messages.success(request, 'successfully Deleted')
        return redirect('brand')

    context = {
        'name':brands
    }
    return render(request, 'ims/delete.html', context)


@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin'])
def DeleteCat(request, pk):
    cats = Category.objects.get(id=pk)
    if request.method == 'POST':
        cats.delete()
        messages.success(request, 'successfully Deleted')
        return redirect('cat')

    context = {
        'name':cats
    }
    return render(request, 'ims/delete.html', context)

@login_required(login_url=('login'))
@allowed_users(allowed_roles=['admin','staff'])
def StaffProduct(request):
    products = Product.objects.all()
           
    context = {
        'products':products,
    }
    return render(request, 'ims/staffproduct.html', context)

def StaffProductDetails(request, pk):
    products = Product.objects.get(id=pk)
    sales_form = SalesForm(request.POST or None, instance=products)
    if sales_form.is_valid():
        products = sales_form.save(commit=False)
        products.quantity -= products.quantity_sold
        products.available = products.quantity
        products.total_price = products.quantity_sold*products.price
        products.save()
        sales_report = ProductReport(
            id = products.id,
            last_updated = products.last_updated,
            name = products.name,
            quantity_sold = products.quantity_sold,
            count = products.count,
            quantity_restocked = products.quantity_restocked,
            available = products.available,
            variance = products.variance,
            price = products.price,
            total_price = products.total_price
        )
        sales_report.save()
        messages.success(request, 'successfully updated')    
        return redirect('staffpage')
    
    context ={
        'products' : products,
        'sales_form' : sales_form,      
    }
    return render(request, 'ims/productdetails_staff.html', context)

def recordCount(request, pk):
    products = Product.objects.get(id=pk)
    count_form = CountForm(request.POST or None, instance=products)
    if count_form.is_valid():
        products = count_form.save(commit=False)
        products.variance = products.count - products.available
        products.save()
        count_report = ProductReport(
            id = products.id,
            last_updated = products.last_updated,
            name = products.name,
            quantity_sold = products.quantity_sold,
            count = products.count,

templates/ims/brand.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Brand{% endblock%}

{% block content %}
<br>
<div class="row">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <div class="card card-body">
            <h5>Brands</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Name</th>
                    <th></th>
                    <th></th>
                </tr>
                {% for brands in brands %}
                <tr>
                    <td>{{brands.name}}</td>
                    <td><a href="{% url 'delete_brand' brands.id %}" 
                        class="btn btn-outline-danger" title="Delete">
                            <i class="fa-regular fa-trash-can"></i>
                        </a>&nbsp;
                        <a href="{% url 'update_brand' brands.id %}" 
                        class="btn btn-outline-dark" title="Edit">
                            <i class="fa-regular fa-pen-to-square"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md py-3">
            <a class="btn btn-outline-primary" href="" data-toggle="modal" data-target="#exampleModal2">Create Brand</a>
            <!--Modal-->
            <div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModal2Label" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModal2Label">Add Brand</h5>
                      <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="" class="py-3">
                            {% csrf_token %}
                            {{form}}
                            <div class="py-3">
                            <input type="submit" name="Submit" class="btn btn-outline-info">
                            </div>
                        </form>
                    </div>
                  </div>
                </div>
            </div>
            <!--Modal end-->
        </div>
    </div>
</div>   

{% for message in messages %}
    {% if message.tags == 'success' %}
    <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
    <script>
        var m = "{{ message }}";
        swal.fire("perfect !", m, "success")
    </script>
    {% endif %}
{% endfor %}

{% endblock %}
    

    

templates/ims/count.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Product Details{% endblock %}
{% block content %}
<br>
<div class="row">
    <div class="col-lg-12 col-md-6 col-sm-12">
        <h4>{{products.name}}</h4>
        <span>
            <a href="{% url 'staffpage' %}" class="" id="arrow">
              <b><i class="bi bi-arrow-left-circle-fill" style="font-size:30px; color:black;"></i></b>
            </a>
        </span>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Store Count</th>
                    <th>Last Updated</th>
                </tr>
                
                <tr>
                    <td>{{products.name}}</td>
                    <td>{{products.count}}</td>
                    <td>{{products.updated_at}}</td>
                    
                </tr>
                
            </table>
            <div class="row d-flex justify-content-center">
                <a class="btn btn-outline-info btn-sm col-3 mx-2" href="" data-toggle="modal" data-target="#countModal">Record Count</a>
            </div>
        </div>
    </div>
</div>    

<!--Modal-->
<div class="modal fade" id="countModal" tabindex="-1" aria-labelledby="countModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="countModalLabel">Record Count</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post" action="" class="py-3">
                {% csrf_token %}
                {{count_form}}
                <div class="py-3">
                <input type="submit" name="Submit" class="btn btn-outline-info">
                </div>
            </form>
        </div>
      </div>
    </div>
</div>
<!--Modal end-->
<script>
    const formInInput = document.querySelector('#id_count');
        
    console.log(formInInput.value);

    formInInput.value = '';

</script>

{% for message in messages %}
    {% if message.tags == 'success' %}
    <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
    <script>
        var m = "{{ message }}";
        swal.fire("perfect !", m, "success")
    </script>
    {% endif %}
{% endfor %}

{% endblock %}

templates/ims/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block content %}
{% include 'ims/status.html' %}

<script src="{% static 'js/chart.min.js'%}"></script>


<br>
<div class="row mb-3">
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <div class="col-md"></br>
            <div class="card card-body">
              <canvas id="myChart"></canvas>
              <script>
                const ctx = document.getElementById('myChart').getContext('2d');
                const myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: [{% for reports in reports %}'{{ reports.name }}', {% endfor %}],
                        datasets: [{
                            label: 'largest recent sales',
                            data: [{% for reports in reports %}'{{ reports.quantity_sold }}', {% endfor %}],
                            backgroundColor: [
                                'rgba(255, 99, 132, 0.2)',
                                'rgba(54, 162, 235, 0.2)',
                                'rgba(255, 206, 86, 0.2)',
                                'rgba(75, 192, 192, 0.2)',
                                'rgba(153, 102, 255, 0.2)',
                                'rgba(255, 159, 64, 0.2)'
                            ],
                            borderColor: [
                                'rgba(255, 99, 132, 1)',
                                'rgba(54, 162, 235, 1)',
                                'rgba(255, 206, 86, 1)',
                                'rgba(75, 192, 192, 1)',
                                'rgba(153, 102, 255, 1)',
                                'rgba(255, 159, 64, 1)'
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        title: {
                          display:true,
                          text: 'Product sale summary'
                        },
                    }
                });
              
              </script>
              
            </div>
        </div>
    </div>
    
    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
        <div class="col-md"> <br/>
            <div class="card card-body">
                <canvas id="myChart1"></canvas>
                <div>
                  <script>
                   
                  
                    const data = {
                      labels: [{% for report in report %}'{{ report.name }}', {% endfor %}],
                      datasets: [{
                        label: 'recently restocked',
                        backgroundColor: 'rgb(255, 99, 132)',
                        borderColor: 'rgb(255, 99, 132)',
                        data: [{% for report in report %}'{{ report.quantity_restocked }}', {% endfor %}],
                      }]
                    };
                  
                    const config1 = {
                      type: 'line',
                      data: data,
                      options: {}
                    };
                    const myChart1 = new Chart(
                      document.getElementById('myChart1'),
                      config1
                    );
                    
                  </script>
                </div>
            </div>
        </div>
    </div>
</div>
  
  
{% endblock %}

templates/ims/productdetails.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Product Details{% endblock %}
{% block content %}
<br>
<div class="row">
    <div class="col-md-12">
        <h4>Product</h4>
        <span>
          <a href="{% url 'product' %}" class="" id="arrow">
            <b><i class="bi bi-arrow-left-circle-fill" style="font-size:30px; color:black;"></i></b>
          </a>
        </span>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Reorder Level</th>
                    <th>Last Updated</th>
                </tr>
                
                <tr>
                    <td>{{products.name}}</td>
                    <td>{{products.quantity}}</td>
                    <td>{{products.price}}</td>
                    <td>{{products.reorder_level}}</td>
                    <td>{{products.last_updated}}</td>
                    
                </tr>
                
            </table>
            <div class="row d-flex justify-content-center">
                <a class="btn btn-outline-primary btn-sm mx-2 col-3" href="" data-toggle="modal" data-target="#reorderModal">Set Reorder Level</a>
                <a class="btn btn-outline-success btn-sm col-3 mx-" href="" data-toggle="modal" data-target="#restockModal">Restok</a>
               
            </div>
        </div>
    </div>
</div>    


<!--Modal-->
<div class="modal fade" id="restockModal" tabindex="-1" aria-labelledby="restockModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="restockModalLabel">Restock Product</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form method="post" action="" class="py-3">
              {% csrf_token %}
              {{restock_form}}
              <div class="py-3">
              <input type="submit" name="Submit" class="btn btn-outline-info">
              </div>
          </form>
      </div>
    </div>
  </div>
</div>
<!--Modal end-->
 <!--Modal-->
 <div class="modal fade" id="reorderModal" tabindex="-1" aria-labelledby="reorderModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="reorderModalLabel">Set Reorder Level</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post" action="" class="py-3">
                {% csrf_token %}
                {{reorder_form}}
                <div class="py-3">
                <input type="submit" name="Submit" class="btn btn-outline-info">
                </div>
            </form>
        </div>
      </div>
    </div>
</div>
<!--Modal end-->
<script>
  const formInInput = document.querySelector('#id_quantity_restocked');
      
  console.log(formInInput.value);

  formInInput.value = '';

</script>

{% for message in messages %}
    {% if message.tags == 'success' %}
    <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
    <script>
        var m = "{{ message }}";
        swal.fire("perfect !", m, "success")
    </script>
    {% endif %}
{% endfor %}

{% endblock %}

templates/ims/productdetails_staff.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Product Details{% endblock %}
{% block content %}
<br>
<div class="row">
    <div class="col-md-12">
        <h4>{{products.name}}</h4>
        <span>
            <a href="{% url 'staffpage' %}" class="" id="arrow">
              <b><i class="bi bi-arrow-left-circle-fill" style="font-size:30px; color:black;"></i></b>
            </a>
        </span>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Reorder Level</th>
                    <th>Last Updated</th>
                </tr>
                
                <tr>
                    <td>{{products.name}}</td>
                    <td>{{products.quantity}}</td>
                    <td>{{products.price}}</td>
                    <td>{{products.reorder_level}}</td>
                    <td>{{products.updated_at}}</td>
                    
                </tr>
                
            </table>
            <div class="row d-flex justify-content-center">
                <a class="btn btn-outline-warning btn-sm mx-2 col-3" href="" data-toggle="modal" data-target="#saleModal">Record Sales</a>
            </div>
        </div>
    </div>
</div>    

<!--Modal-->
<div class="modal fade" id="saleModal" tabindex="-1" aria-labelledby="saleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="saleModalLabel">Record Sales</h5>
          <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="post" action="" class="py-3" id="formIn">
                {% csrf_token %}
                {{sales_form}}
                <div class="py-3">
                <input type="submit" name="Submit" class="btn btn-outline-info" id="subForm">
                </div>
            </form>
        </div>
      </div>
    </div>
</div>
<!--Modal end-->
<script>
    const formInInput = document.querySelector('#id_quantity_sold');
        
    console.log(formInInput.value);

    formInInput.value = '';

</script>

{% for message in messages %}
    {% if message.tags == 'success' %}
    <script src="{% static 'js/sweetalert2.all.min.js' %}"></script>
    <script>
        var m = "{{ message }}";
        swal.fire("perfect !", m, "success")
    </script>
    {% endif %}
{% endfor %}

{% endblock %}

templates/ims/staff.html
{% extends 'base.html' %}

{% block title %}staff page{% endblock %}

{% block content %}
{% include 'ims/status.html' %}
<br>
<div class="row">
    <div class="col">
        <div class="card card-body">

        </div>
    </div>
</div
{% endblock %}